# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/ahmedmhk/UnrealEngine/Linux_Unreal_Engine_5.6.0

TARGETS = \
	CharacterCreationCpp-Android-DebugGame  \
	CharacterCreationCpp-Android-Development  \
	CharacterCreationCpp-Android-Shipping  \
	CharacterCreationCpp-Linux-DebugGame  \
	CharacterCreationCpp-Linux-Development  \
	CharacterCreationCpp-Linux-Shipping  \
	CharacterCreationCpp-LinuxArm64-DebugGame  \
	CharacterCreationCpp-LinuxArm64-Development  \
	CharacterCreationCpp-LinuxArm64-Shipping  \
	CharacterCreationCpp \
	CharacterCreationCppEditor-Linux-DebugGame  \
	CharacterCreationCppEditor-Linux-Development  \
	CharacterCreationCppEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend CharacterCreationCppEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug CharacterCreationCppEditor-Linux-Debug


CharacterCreationCpp-Android-DebugGame:
	 $(BUILD) CharacterCreationCpp Android DebugGame  -Project="/home/ahmedmhk/Documents/Unreal Projects/CharacterCreationCpp/CharacterCreationCpp.uproject" $(ARGS)

CharacterCreationCpp-Android-Development:
	 $(BUILD) CharacterCreationCpp Android Development  -Project="/home/ahmedmhk/Documents/Unreal Projects/CharacterCreationCpp/CharacterCreationCpp.uproject" $(ARGS)

CharacterCreationCpp-Android-Shipping:
	 $(BUILD) CharacterCreationCpp Android Shipping  -Project="/home/ahmedmhk/Documents/Unreal Projects/CharacterCreationCpp/CharacterCreationCpp.uproject" $(ARGS)

CharacterCreationCpp-Linux-DebugGame:
	 $(BUILD) CharacterCreationCpp Linux DebugGame  -Project="/home/ahmedmhk/Documents/Unreal Projects/CharacterCreationCpp/CharacterCreationCpp.uproject" $(ARGS)

CharacterCreationCpp-Linux-Development:
	 $(BUILD) CharacterCreationCpp Linux Development  -Project="/home/ahmedmhk/Documents/Unreal Projects/CharacterCreationCpp/CharacterCreationCpp.uproject" $(ARGS)

CharacterCreationCpp-Linux-Shipping:
	 $(BUILD) CharacterCreationCpp Linux Shipping  -Project="/home/ahmedmhk/Documents/Unreal Projects/CharacterCreationCpp/CharacterCreationCpp.uproject" $(ARGS)

CharacterCreationCpp-LinuxArm64-DebugGame:
	 $(BUILD) CharacterCreationCpp LinuxArm64 DebugGame  -Project="/home/ahmedmhk/Documents/Unreal Projects/CharacterCreationCpp/CharacterCreationCpp.uproject" $(ARGS)

CharacterCreationCpp-LinuxArm64-Development:
	 $(BUILD) CharacterCreationCpp LinuxArm64 Development  -Project="/home/ahmedmhk/Documents/Unreal Projects/CharacterCreationCpp/CharacterCreationCpp.uproject" $(ARGS)

CharacterCreationCpp-LinuxArm64-Shipping:
	 $(BUILD) CharacterCreationCpp LinuxArm64 Shipping  -Project="/home/ahmedmhk/Documents/Unreal Projects/CharacterCreationCpp/CharacterCreationCpp.uproject" $(ARGS)

CharacterCreationCpp: CharacterCreationCpp-Linux-Development

CharacterCreationCppEditor-Linux-DebugGame:
	 $(BUILD) CharacterCreationCppEditor Linux DebugGame  -Project="/home/ahmedmhk/Documents/Unreal Projects/CharacterCreationCpp/CharacterCreationCpp.uproject" $(ARGS)

CharacterCreationCppEditor-Linux-Development:
	 $(BUILD) CharacterCreationCppEditor Linux Development  -Project="/home/ahmedmhk/Documents/Unreal Projects/CharacterCreationCpp/CharacterCreationCpp.uproject" $(ARGS)

CharacterCreationCppEditor: CharacterCreationCppEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/ahmedmhk/Documents/Unreal Projects/CharacterCreationCpp/CharacterCreationCpp.uproject" -Game 

.PHONY: $(TARGETS)
